### ISSUE TITLE
app fails when songs has multilang

### ISSUE THREAD

**Issue by umsaenga** [youkaclub/youka-desktop#11]
In the even you didn't already know, the app fails to provide transliteration / captions when a song is sang in two languages.  Take for example "Justin Bieber – Despacito ".

Cheers

**Comment by youkaclub** [comment]
I'll check it out, thanks

**Comment by umsaenga** [comment]
it also doesn't quite sync the captions for Rap genre.  Take for example: 'Rockstar' by DaBaby Featuring Roddy Ricch (youtubeID: m0F6Gm7frfY)

**Comment by youkaclub** [comment]
I’m checking, thanks
