### ISSUE TITLE
download song

### ISSUE THREAD

**Issue by vipermetcaff** [youkaclub/youka-desktop#25]
i can only download   song then i have to go  into the sync editor to download the orignal audio

**Comment by youkaclub** [comment]
I don’t understand the question

**Comment by vipermetcaff** [comment]
once  i download a song audio instermental then switch to orignal it wont let me download it again

**Comment by youkaclub** [comment]
Thanks for reporting this problem, I'll fix it soon

**Comment by youkaclub** [comment]
fixed

**Comment by vipermetcaff** [comment]
works great thanks
