### ISSUE TITLE
I want to be a distributor or do affiliate marketing for the software

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [youkaclub/youka-desktop#26]
Hi,
I have many karaoke channels with lots of subscribers. I want to help sell YouKa as a musical software using the traffic driven from my karaoke channels. Is there a way to collaborate on this? To automate things, it helps if the software takes license codes in addition to Patreon subscription. 
Looking forward to hearing from you!
Daniel

**Comment by youkaclub** [comment]
Let’s talk privately on Discord
