### ISSUE TITLE
Don't see a download option

### ISSUE THREAD

**Issue by sudeepghatak** [youkaclub/youka-desktop#7]
Hi,
This works brilliantly. Great job guys!
I don't see a download option as shown in the demo. 

<img width="960" alt="jhyrVIrQoH" src="https://user-images.githubusercontent.com/12538280/81881293-e9274080-95e3-11ea-893b-a901ffdb0fdc.png">

Thanks
Sudeep

**Comment by youkaclub** [comment]
Please make sure you run the latest version.
- Restart Youka
- In case of update message in the bottom, click on it
