### ISSUE TITLE
I stuck in "Server is processing your song" message.

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [youkaclub/youka-desktop#8]
I stuck in "Server is processing your song" message. No song was processed for me. Is the program still working as of now or have you closed the server?

**Comment by lenaten** [comment]
The server is up but the queue is full, please try again later..

**Comment by youkaclub** [comment]
The server is up but the queue is full, please try again later..

**Comment by Daniel-Trung-Nguyen** [comment]
Thanks for the reply! Is there a way I can install and run this on the localhost to avoid the queue?

**Comment by youkaclub** [comment]
The server side infra is too complicated right now, maybe in the future

**Comment by Daniel-Trung-Nguyen** [comment]
I have been using the setup of Spleeter from here https://github.com/thepirat000/spleeter-api on the localhost. However, it does not have the audio lyrics alignment capacity like yours. Will be waiting for future deployments of your project. Thanks for the awesome software!

**Comment by youkaclub** [comment]
Yeah the alignment is the hardest part.. Your products looks very good as well

**Comment by Daniel-Trung-Nguyen** [comment]
Awesome. Keep up the good work!
