### ISSUE TITLE
Youka on browser displays nothing (Electron app works perfectly)

### ISSUE THREAD

**Issue by topotech** [youkaclub/youka-desktop#9]
Going to  http://localhost:3000 displays a seemingly blank page. I'm testing this on Manjaro with Firefox 76.0.1 64 bits. 

Seeing the source of the page shows that page is actually not blank, and all GET request end successfully with a 200 HTTP status.

In the console I can see the error

```
ReferenceError: require is not definedexternal "crypto":1
    crypto external "crypto":1
    Webpack 25
        __webpack_require__
        fn
        js
        __webpack_require__
        fn
        js
        __webpack_require__
        fn
        js
        __webpack_require__
        fn
        js
        __webpack_require__
        fn
        js
        __webpack_require__
        fn
        js
        __webpack_require__
        fn
        0
        __webpack_require__
        checkDeferredModules
        webpackJsonpCallback
        <anonymous>
```
I know this happens because require is a Node thing, but I wondered if it was possible to run the App as a server in the local network.

**Comment by youkaclub** [comment]
Since the browser can't execute node functions the answer is no.
